# Generated by Django 3.2.6 on 2021-10-21 02:01

from django.db import migrations
import useraccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_remove_useraccount_favorite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='favorite_color',
            field=useraccount.models.RGBcolorField(max_length=6, null=True),
        ),
    ]
