# Generated by Django 3.2.6 on 2021-10-21 01:46

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=140, validators=[post.models.validate_no_bad_words]),
        ),
    ]
