# Generated by Django 3.2.6 on 2021-10-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile_photos'),
        ),
    ]
